#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "Building WASM..."
cd "$PROJECT_ROOT"
wasm-pack build crates/renskriv-wasm \
    --target web \
    --out-dir "$PROJECT_ROOT/extension/src/wasm" \
    --out-name renskriv_wasm

# Remove unnecessary files generated by wasm-pack
rm -f "$PROJECT_ROOT/extension/src/wasm/.gitignore"
rm -f "$PROJECT_ROOT/extension/src/wasm/package.json"

echo "WASM build complete. Output in extension/src/wasm/"
ls -lh "$PROJECT_ROOT/extension/src/wasm/"
